title: Cyrus Sun 
description: "Class of 2026"
owner_name: Cyrus Sun
github_username: cyrusun-0505
github_repo: "cyrus_student2025" 
baseurl: "/cyrus_student2025" 
future: true
remote_theme: jekyll/minima

social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md
url: "http://127.0.0.1:4600" # 你的本地服务器地址
baseurl: "/cyrus_student2025" # 日志中显示的子路径